GET http://localhost:3000/api/v1/products
Content-Type: application/json

###

GET http://localhost:3000/api/v1/products/256
Content-Type: application/json

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name": "Tahu Bakso",
  "price": 2000,
  "stock": 200
}

###

PUT http://localhost:3000/api/v1/products/256
Content-Type: application/json
// affected rows => row yg berhasil diupdate

{
  "name": "Tahu Aci Jos",
  "price": 2500,
  "stock": 300
}

###
DELETE http://localhost:3000/api/v1/products/256
Content-Type: application/json

###

GET http://localhost:3000/api/v1/orders
Content-Type: application/json

###

GET http://localhost:3000/api/v1/orders/1
Content-Type: application/json

###
GET http://localhost:3000/api/v1/users
Content-Type: application/json

###
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "{ products { name price stock } customers { name phone } orders { date qty totalAmount product { name } customer { name } }}"
}

###
GET http://localhost:3000/graphql?query={hello}
Content-Type: application/json